### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by NL66278** [Coding-Dodo/OWL-JavaScript-Project-Starter#1]
Thanks for creating the Owl tutorial and this project!

Running the first $ npm run dev immediately results in an incredible amount of errors. Apparently the npm install installs more files then are in a full Odoo installation, and then rollup wants to watch all of those for changes, instead of just the files we are working on.

Is there any way to disable this watch functionality? I am quite able to start npm run dev myself after changing some sources... I tried to remove the -w option from rollup in package.json, but that did not have any effect.

(node:20214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7283)
(node:20214) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/openeyedev/var/projects/real_world_app/node_modules/.bin/xml-js'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/openeyedev/var/projects/real_world_app/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/openeyedev/var/projects/real_world_app/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/openeyedev/var/projects/real_world_app/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/openeyedev/var/projects/real_world_app/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/openeyedev/var/projects/real_world_app/node_modules/chokidar/lib/nodefs-handler.js:629:21)

**Comment by NL66278** [comment]
Oh, and I read I could prevent the message by increasing the os limit on watches, but I think this is really not the way, undermining OS stability for an unneeded watch on tens of thousands of files.

**Comment by PhilDL** [comment]
Hi @NL66278, thank you for your feedback.

The node_modules folder has been added to the Rollup.js config in the last commit, it should be much better and faster.
If you still don't want the "watch" functionality, go into your package.json file and change the `scripts` part

From 
```
"scripts": {
    "test": "jest",
    "build": "NODE_ENV=production rollup -c",
    "dev": "rollup -c -w"
  },
```

To:
```
"scripts": {
    "test": "jest",
    "build": "NODE_ENV=production rollup -c",
    "dev": "rollup -c"
  },
```

Please tell me if it fixed your issue so i can close it.

Have a nice day.
